export const STORAGE_KEYS = {
    LIST_DATA: 'LIST_DATA',
    LIST_PAGE: 'LIST_PAGE',
    LIST_UPDATED_AT: 'LIST_UPDATED_AT',
    GURU_GRANTH_SHIB_JI_BANI_DATA: 'GURU_GRANTH_SHIB_JI_BANI_DATA',
    GURU_GRANTH_SHIB_JI_BANI_PAGE: 'GURU_GRANTH_SHIB_JI_BANI_PAGE',
    GURU_GRANTH_SHIB_JI_BANI_UPDATED_AT: 'GURU_GRANTH_SHIB_JI_BANI_UPDATED_AT',
    GURU_GRANTH_SHIB_JI_BANI_HAS_NEXT_PAGE: 'GURU_GRANTH_SHIB_JI_BANI_HAS_NEXT_PAGE',
    GURBANI_KHOJ_FAVOURITES: 'GURBANI_KHOJ_FAVOURITES',
    GURBANI_KHOJ_BOOKMARK: 'GURBANI_KHOJ_BOOKMARK',
};
